name: "R: Windows"
description: "Run R CMD check and related checks on Windows"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: "devel"

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install
      shell: bash
      run: |
        R -f tools/rpkg/dependencies.R

    - name: Build
      shell: bash
      run: |
        cd tools/rpkg
        ./configure
        R CMD build .
        R CMD INSTALL duckdb_*.tar.gz
        (cd tests && R -f testthat.R)
        _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_PKG_SIZES_=FALSE R CMD check --as-cran --no-manual -o /tmp duckdb_*.tar.gz
        if egrep 'NOTE|WARNING|ERROR' /tmp/duckdb.Rcheck/00check.log ; then exit 1; fi
