name: R
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
      - "examples/**"
      - "test/**"
      - "tools/juliapkg/**"
      - "tools/nodejs/**"
      - "tools/pythonpkg/**"
      - ".github/workflows/**"
      - "!.github/workflows/R.yml"
      - "!.github/actions/r/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
  r-test-extension:
    name: Extension for R test
    runs-on: ubuntu-latest
    container: ubuntu:16.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ubuntu_16_setup
        with:
          openssl: 1

      - uses: ./.github/actions/build_extensions
        with:
          run_tests: 0
          static_link_build: 1

      - uses: actions/upload-artifact@v2
        with:
          name: r-test-extensions
          path: |
            build/release/extension/*/*.duckdb_extension

  rstats-linux:
    name: R Package Linux
    runs-on: ubuntu-20.04
    needs: r-test-extension
    env:
      LIBARROW_BINARY: "false"
      ARROW_RUNTIME_SIMD_LEVEL: "AVX2"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/r/linux

  rstats-linux-debug:
    name: R Package Linux debug mode
    runs-on: ubuntu-20.04
    needs: rstats-linux

    env:
      LIBARROW_BINARY: "false"
      ARROW_RUNTIME_SIMD_LEVEL: "AVX2"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/r/linux-debug

  rstats-windows:
    name: R Package Windows
    runs-on: windows-latest
    needs: rstats-linux

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/r/windows

  rubsan:
    name: R UBSAN
    runs-on: ubuntu-latest
    needs: rstats-linux

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/r/ubsan
